### ISSUE TITLE
ヘッダーの画像が崩れないようにする

### ISSUE THREAD

**Issue by nichesuch** [kaji-buntan-project/kaji-buntan#14]
単純にアスペクト比を保とうとすると、小さくなりすぎる。
![image](https://user-images.githubusercontent.com/2096703/170812869-de993370-e5ed-462e-8d19-e2980216c661.png)

林さんに造ってもらって、これを入れてみる予定
![image](https://user-images.githubusercontent.com/2096703/170812691-34b64a61-bc5a-4797-9f28-31b8282d613c.png)

他バージョン
![image](https://user-images.githubusercontent.com/2096703/170812701-0ff9fb59-692c-4b15-8cab-1f083f503285.png)

![image](https://user-images.githubusercontent.com/2096703/170812705-16a8aa97-9426-4c60-9899-c373b5118693.png)

**Comment by osoken** [comment]
closed via #15
